version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    command: npm run dev
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - DB_NAME=nginxproxy_db
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: npm run dev
    environment:
      - NODE_ENV=development


  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nginxproxy_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: