events {}

http {
    server {
        listen 8080;

        root /usr/share/nginx/html;
        index index.html index.htm;

        include /etc/nginx/mime.types;  # ОБОВʼЯЗКОВО

        # Проксі для API
        location /api/ {
            proxy_pass http://backend:4000/api/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # Видача frontend
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
